### ISSUE TITLE
co-occurring HFOs across tetrodes

### ISSUE THREAD

**Issue by Aleman-Z** [DR-DOH/HFO-detector#12]
Currently the detection is done with respect to the start of the event. But it would be more reliable if done with respect to the peak of the event.

https://github.com/DR-DOH/HFO-detector/blob/187a466eea2a66b24f539395f52ac50aff60f0ea/Scripts%20Updated/tetrode_ripples.m#L29

**Comment by DR-DOH** [comment]
ok yeah works
