### ISSUE TITLE
Use of '\' may need to change to '/'. 

### ISSUE THREAD

**Issue by Aleman-Z** [DR-DOH/HFO-detector#9]
https://github.com/DR-DOH/HFO-detector/blob/b2d3208ae3ac0b30c2938d7d966bdcb315ab5279/Scripts%20Updated/all_sleep.m#L29

At least for Lisa's computer this was required. Not sure about your computer.

**Comment by Aleman-Z** [comment]
same for post_trial5.m

**Comment by DR-DOH** [comment]
Yeah, linux and windows issue.
linux requires frontslash and windows requires backslash
